Feat creator register page
dashakrolik/Idealists-client pull request #153
Opened 2020-12-02 14:55 UTC by Emnetdegafe

- Cofounder  register page
- Cofounder login page ready
- Reset your password on login

2020-12-03 11:49 UTC, DannyS-stack approved these changes
LGTM!

Only feedback I have is that you have a lot of styling rules in your components, would maybe be nicer to have it in a separate file. I don't think it it important enough to change it so looks good enough.

2020-12-04 12:00 UTC, dashakrolik requested changes

2020-12-04 12:00 UTC, dashakrolik commented on src/components/Cofounder/CofounderRegisteration.js
> +    console.log('formData', formData)
delete console.log

2020-12-04 12:00 UTC, dashakrolik commented on src/components/Cofounder/CofounderRegisteration.js
> +    };
It seems like this is duplicate code above? Can we not reuse the other object that we are using for the other registration?

2020-12-04 12:00 UTC, dashakrolik commented on src/components/Cofounder/CofounderRegisteration.js
> +
Is this all copy paste? Let's make the login form reusable instead please.

2020-12-04 12:46 UTC, Emnetdegafe commented on src/components/Cofounder/CofounderRegisteration.js
> +    };
Not really, we needed to add role input to the form thus we needed to change it. It's a radio button that is required to be filled.

2020-12-05 13:26 UTC, closed without merging

2020-12-05 13:26 UTC, Emnetdegafe commented
Closed due to changes with LoginForm restructure and bug fix

2020-12-07 08:25 UTC, dashakrolik reviewed
good job