Feat/creator catalyst dashboard
dashakrolik/Idealists-client pull request #156
Opened 2020-12-06 18:40 UTC by SupriyaShekar123

# What does this pull request do?
In this pull request a form to upload cofounder profile video is made and the video is submitted to Cloudinary account.
Another form is made with link to personality test. 

![Idealists_giphy](https://user-images.githubusercontent.com/58122382/101289050-41c95f80-37fa-11eb-99e7-e5f7a2384ae6.gif)

2020-12-06 20:37 UTC, DannyS-stack requested changes
Good work Supriya! Maybe it would be a good idea to go over it 1 more time and remove all the console.logs.

2020-12-07 08:27 UTC, SupriyaShekar123 commented
> Good work Supriya! Maybe it would be a good idea to go over it 1 more time and remove all the console.logs.

Thank you Danny. Yes I will remove all console.logs and push the code.

2020-12-07 08:29 UTC, dashakrolik requested changes

2020-12-07 08:29 UTC, dashakrolik commented on src/App.js
> +                      // authState={this.state.auth}
delete unused code

2020-12-07 08:29 UTC, dashakrolik commented on src/App.js
> +                      // login={this.requestLoginUser}
delete unused code

2020-12-07 08:29 UTC, dashakrolik commented on src/components/Catalyst/ProfileUpdateForm.js
> +// import { baseUrl } from '../../../constants';
delete unused code

2020-12-07 08:29 UTC, dashakrolik commented on src/components/Cofounder/CofounderPersonalityTest.js
> +        setSuccessMsg(true)
delete console.logs

2020-12-07 08:29 UTC, dashakrolik commented on src/components/Cofounder/CofounderPersonalityTest.js
> +    const setValue =(e)=>{
Spaces

2020-12-07 08:29 UTC, dashakrolik commented on src/components/Cofounder/CofounderPersonalityTest.js
> +        if(e.target.value.match(format) ){
Spaces

2020-12-07 08:29 UTC, dashakrolik commented on src/components/Cofounder/CofounderPersonalityTest.js
> +                // validationErrors={{matchRegexp:'The result should contain 4 Capital letters.'}}
delete unused code

2020-12-07 08:29 UTC, dashakrolik commented on src/components/Cofounder/CofounderProfileVideo.js
> +  const[successMsg,setSuccessMsg] = useState(false)
Spaces

2020-12-07 08:29 UTC, dashakrolik commented on src/components/Cofounder/CofounderProfileVideo.js
> +     const previewVideo = (video)=>{
spaces....

2020-12-07 08:29 UTC, dashakrolik commented on src/components/Cofounder/CofounderProfileVideo.js
> +    e.preventDefault()
Indentation, please fix it everywhere

2020-12-07 09:16 UTC, SupriyaShekar123 commented on src/components/Cofounder/CofounderProfileVideo.js
> +    e.preventDefault()
Okay, Dasha I will make the changes.

2020-12-07 17:12 UTC, dashakrolik approved these changes

2020-12-07 17:13 UTC, dashakrolik commented
> Good work Supriya! Maybe it would be a good idea to go over it 1 more time and remove all the console.logs.

It's been updated!:)

2020-12-08 09:56 UTC, merged

2020-12-08 09:56 UTC, DannyS-stack commented
Looks good, I merged it