Feat/comment editor
dashakrolik/Idealists-client pull request #157
Opened 2020-12-07 09:44 UTC by DarianRushworth

**Comments editable**
Comments made by the specialist are immediately rendered, with all the proper information, all I need to do was tinker with the **useEffect** call. I also placed a icon for the user to be able to edit his or her comment. Upon editing the same form appears with previous data as placeholders. The comment is made and rendered immediately. I also then made sure that only the user that posted the comment can edit it.

2020-12-07 17:15 UTC, dashakrolik requested changes

2020-12-07 17:15 UTC, dashakrolik commented on src/components/SpecialistPortal/Dashboard/SpecialistDashboard.js
>  // import crowdfunding from '../../../res/crowdfunding.png'
delete unused code

2020-12-07 17:15 UTC, dashakrolik commented on src/components/SpecialistPortal/Dashboard/CommentSection/CommentSection.js
>        //   .then((res) => console.log("res.body", res.body));
delete unused

2020-12-08 08:19 UTC, mr-robak approved these changes
looks good!

2020-12-08 09:24 UTC, DarianRushworth commented on src/components/SpecialistPortal/Dashboard/SpecialistDashboard.js
>  // import crowdfunding from '../../../res/crowdfunding.png'
Code deleted, see below for commit.

2020-12-08 09:24 UTC, DarianRushworth commented on src/components/SpecialistPortal/Dashboard/CommentSection/CommentSection.js
>        //   .then((res) => console.log("res.body", res.body));
Code deleted.

2020-12-08 09:32 UTC, nazneen1022 approved these changes
looks good.

2020-12-08 10:43 UTC, dashakrolik approved these changes

2020-12-08 10:43 UTC, dashakrolik commented
Solve merge conflicts and good to merge!

2020-12-08 12:55 UTC, merged