Feat/admin idea  manual control
dashakrolik/Idealists-client pull request #160
Opened 2020-12-07 15:26 UTC by mr-robak

**This is client-side updated solving:**
**Ticket 4**
 - [x] -  make it so, that the admin has to manually move ideas from phase 1 to this phase 2 (automated patent-check). 
- [x] -  make sure the email with the invite is only sent to the idea-person after the admin has manually moved their idea to phase 2. 
- [x] - After phase 2 it can automatically move to phase 3 (which now  the system does not do and has to be done manually by the admin). 
- [x] -  make sure the idea-person’s feedback on the patents is saved into the idea-file, as currently this very valuable feedback is not visible in later phases to specialist
- [x] -    from phase 3,  also temporarily make it so that we as an admin manually have to push ideas to phase 4 (Second patent check). If possible make it easy to revert these 2 manual gates in the coming months by the developers working on it at that time, or even better by the admin within the platform with for example some switches.

**For server-side update to this ticket check the following PR: **
[https://github.com/dashakrolik/idealists-server/pull/51](https://github.com/dashakrolik/idealists-server/pull/51)

2020-12-07 17:17 UTC, dashakrolik approved these changes

2020-12-07 17:17 UTC, dashakrolik requested changes
Please solve the merge conflicts. Otherwise looks good to merge!

2020-12-08 09:28 UTC, DarianRushworth commented
Looks amazing, conflicts were on my spinner so I cleared the conflicts. Great work Marcin!!!

2020-12-08 09:28 UTC, DarianRushworth approved these changes

2020-12-08 09:37 UTC, nazneen1022 approved these changes
code looks good and clean, great job.

2020-12-08 13:14 UTC, merged