Added another spinner
dashakrolik/Idealists-client pull request #164
Opened 2020-12-08 15:52 UTC by DarianRushworth

Added another spinner after agreement is made with a 3 sec timeout for all the data to be collected and stored correctly.

2020-12-09 15:25 UTC, mr-robak approved these changes
looks good!

2020-12-09 20:11 UTC, dashakrolik requested changes

2020-12-09 20:11 UTC, dashakrolik commented on src/components/MyIdea/IdeaSubmission/CompleteSubmission.js
> +        };
Let's please use a different implementation. You need to add a block called .finally() In that part you will set loading to false. We never know how long this async operation will take. 3 seconds? What if it will take 5 seconds?

2020-12-09 20:11 UTC, dashakrolik commented on src/components/MyIdea/IdeaSubmission/CompleteSubmission.js
> +        };
Let's make sure that we use this implementation consistently.
Example:

const yourFunction = () => {
setLoading(true);

request
    .post(`${baseUrl}/ideas`)
    .set("Authorization", `Bearer ${props.authState.token}`)
    .send({ idea: dataToSend, industryIdea: dataIndustryToSend })
    .then(do something)
    .catch(do something with the error)
    .finally(() => setLoading(false)
}

2020-12-10 14:10 UTC, DarianRushworth commented on src/components/MyIdea/IdeaSubmission/CompleteSubmission.js
> +        };
I fixed this issue, I have another timeout function in the login. I am leaving that for now. As the request is in a parent component and need a lot of props to be carried across.

2020-12-11 10:17 UTC, merged