Feat/cofounder profile
dashakrolik/Idealists-client pull request #166
Opened 2020-12-09 16:24 UTC by SupriyaShekar123

# What does this pull request do?

In this pull request, small changes are made in cofounder profile video page and  cofounder personality test. Also made a new component Cofounder welcome page. It has information on how to complete the registration process. Added profile form, where the cofounder answers some questions. All the components are linked.

2020-12-09 17:40 UTC, Emnetdegafe commented on src/components/Cofounder/CofounderStart.js
> +		console.log('props', props);
There are some logs that we need to remove.

2020-12-09 17:40 UTC, Emnetdegafe commented on src/components/Cofounder/CofounderDashboard.js
> +	const [ user, setUserData ] = useState({});
I understand this is now in a new component.

2020-12-09 17:41 UTC, Emnetdegafe approved these changes
Some console logs, except for that, it looks good to me.

2020-12-09 20:14 UTC, dashakrolik requested changes

2020-12-09 20:14 UTC, dashakrolik commented on src/components/Cofounder/CofounderPersonalityTest.js
> +		const response = await fetch(`${baseUrl}/users`, {
We do not use the fetch API, please use request, same as in the rest of the app :)

2020-12-10 09:44 UTC, SupriyaShekar123 commented on src/components/Cofounder/CofounderPersonalityTest.js
> +		const response = await fetch(`${baseUrl}/users`, {
Actually my prettier is not working so had indentation problems, so Reinko Pulled my branch and formated my code and made a new pull request. So we do not want to merge this branch. I have informed Reinko. He will be making the changes.

2020-12-10 14:29 UTC, SupriyaShekar123 commented on src/components/Cofounder/CofounderPersonalityTest.js
> +		const response = await fetch(`${baseUrl}/users`, {
I have made the request using super agent(same as in the rest of the app :)). I have removed all the console logs. Please review the code.

2020-12-10 14:36 UTC, DannyS-stack approved these changes

2020-12-11 08:55 UTC, merged